= Необходимые ресурсы

[#hardware]
== Необходимое техническое обеспечение

Специальные требования не предъявляются.

[#software]
== Необходимое программное обеспечение

.Операционная система:
// * Microsoft Windows Server 2008 R2 и выше.
* Astra Linux Special Edition {l-1}.
* Astra Linux Special Edition {l-1-1}.

.Обязательное программное обеспечение:
* Microsoft
// .NET Framework
{net-r} --
// при установке на Linux
можно загрузить с https://dotnet.microsoft.com/en-us/download/dotnet/6.0[сайта Microsoft].
* Microsoft {asp-bundle} и выше.

[#browser]
.Для работы в Менеджере решений необходим один из следующих веб-браузеров:
* {edge-c} (на базе Chromium).
* {chrome-v} (для OC Windows и для OC Android).
* Google Chromium {chromium-v} и выше (для ОС Linux).
* {yandex} (для ОС Windows).
* {safari}.

[#docsvision]
== Требования к системе {dv}

{sm} совместим с системой {dv}.

На серверах {dv} должен быть выбран протокол подключения клиентов: `HTTP+SOAP` или `WCF TCP сервис`.

.Модули {dv}:
* Серверная часть модуля _{pl}_ версии {pl-v} и выше.
* Серверная часть модуля _{wincl}_ версии {win-v} и выше.
* Серверная часть модуля _{bo}_ версии {bo-v} и выше.
* Серверная часть модуля _{wf}_ версии {wf-v} и выше.
* Серверная часть модуля _Служба {ws}_ версии {ws-v}. Версия 5.5.2 не поддерживается.

[#database]
== Требования к СУБД

Для хранения данных {of-sm} требуется одна из следующих СУБД:

.СУБД:
* {mssql}:
** {mssql} Server {ms-sql-v-1}.
** {mssql} Server {ms-sql-v-2}.
** {mssql} Server {ms-sql-v-3}.
*** для {mssql} Server {ms-sql-v-4}.
*** для {mssql} {ms-sql-v-5}.
** *Служба агента SQL Server (SQL Server Agent) -- установлена и запущена*.
* {pgsql}:
** {pg-sql-v-1} и выше.
** {pg-sql-v-2} и выше.
** Обязательно должна быть установлена и запущена служба планировщика заданий для {pgsql} pgAgent.

СУБД и {sm} могут быть установлены совместно или раздельно.

[#worker-service]
== Требования к Службе {ws}

{sm} использует для своей работы модуль "Служба {ws}". Данный модуль может быть установлен совместно с Менеджером решений или на отдельном компьютере. Инструкцию по установке и настройке модуля "Служба {ws}" см. xref:6.1@workerservice:admin:install.adoc[в документации модуля Служба {ws}].

// [NOTE]
// ====
// Для установки модуля "Служба {ws}" совместно с Менеджером решений рекомендуется использовать xref:admin:.install-bundle.adoc[Пакетный установщик] {of-sm}.
// ====

[#network]
== Требования к ЛВС

Администратор должен обеспечить возможность подключения процесса {of-sm} к используемым серверам {dv}.

Должны быть разрешены http-подключения с компьютеров пользователей к серверу {of-sm} на порт `5700`.

[#license]
== Лицензия

. Для работы с модулем _{sm}_ лицензия на систему {dv} должна содержать дополнительные опции. Также одна или обе из данных опций должны быть доступны для серверов {dv}, к которым подключается _{sm}_:
+
* _{dv} {sm}. Экспорт_ -- для возможности выгрузки существующего Решения из базы данных {dv}.
+
Лицензия должна быть также доступна на сервере, с которого выгружаются данные.
+
* _{dv} {sm}. Импорт_ -- для возможности загрузки выгруженного Решения в базу данных {dv}.
+
Лицензия должна быть также доступна на который загружаются данные.
+
. Срок, в течении которого возможно обновление системы {dv}, указанный в поле лицензии _Возможность обновления до_, не должен быть превышен. Это значит, что на всех серверах {dv}, участвующих в экспорте и импорте Решений, должна сохраняться возможность обновления.

При отсутствии лицензии или истечении срока обновления пользователи не смогут пользоваться функциями экспорта и/или импорта.
