= Необходимые ресурсы

[#hardware]
== Необходимое техническое обеспечение

Специальные требования не предъявляются.

[#software]
== Необходимое программное обеспечение

Операционная система::
* Microsoft Windows Server 2008 R2 и выше.

Обязательное программное обеспечение::
* Microsoft .NET Framework 4.7.2.

Модули {dv}::
* Серверная часть модуля "{pl}" версии {pl-v} и выше.
* Серверная часть модуля "{wincl}" версии {win-v} и выше.
* Серверная часть модуля "{bo}" версии {bo-v} и выше.
* Серверная часть модуля "{wf}" версии {wf-v} и выше.
* Серверная и клиентская части модуля "Служба {ws}" версии {ws-v}. Версия 5.5.2 не поддерживается.

[#browser]
Веб-браузер::
+
.Для работы в Менеджере решений необходим один из следующих веб-браузеров:
* Google Chrome {chrome-v}.
* Microsoft Edge {edge-v}.

[#docsvision]
== Требования к системе {dv}

{sm} совместим с системой {dv} 5.5.

На серверах {dv} должен быть выбран протокол подключения клиентов: `HTTP+SOAP` или `WCF TCP сервис`.

[#database]
== Требования к СУБД

Для хранения данных {of-sm} требуется одна из следующих СУБД:

* {mssql} Server 2014 -- 2017.
* {pgsql}/Postgres Pro версии 9.6 и выше.

СУБД и {sm} могут быть установлены совместно или раздельно.

[#worker-service]
== Требования к Службе {ws}

{sm} использует для своей работы модуль "Служба {ws}". Данный модуль может быть установлен совместно с Менеджером решений или на отдельном компьютере. Инструкцию по установке и настройке модуля "Служба {ws}" см. xref:workerservice:admin:install.adoc[в документации модуля Служба {ws}].

[NOTE]
====
Для установки модуля "Служба {ws}" совместно с Менеджером решений рекомендуется использовать xref:admin:install-bundle.adoc[Пакетный установщик] {of-sm}.
====

Служба {ws} должна быть установлена и запущена.

WARNING: {sm} предъявляет дополнительные программные требования к компьютеру, на котором установлен модуль "{dv} 5. Служба {ws}".

.На компьютере должны быть установлены (без настройки) базовые модули {dv}:
* Серверная часть модуля "{dv} 5. {pl}" версии {pl-v} и выше.
* Серверная часть модуля "{dv} 5. {wincl}" версии {win-v} и выше.
* Серверная часть модуля "{dv} 5. {bo}" версии {bo-v} и выше.
* Серверная часть модуля "{dv} 5. {wf}" версии {wf-v} и выше.

[#network]
== Требования к ЛВС

Администратор должен обеспечить возможность подключения процесса {of-sm} к используемым серверам {dv}.

Должны быть разрешены http-подключения с компьютеров пользователей к серверу {of-sm} на порт `5000`.

[#license]
== Лицензия

. Для работы с модулем "{dv} 5. {sm}" лицензия на систему {dv} должна содержать дополнительные опции. Также одна или обе из данных опций должны быть доступны для серверов {dv}, к которым подключается {sm}:
+
* _{dv} {sm}. Экспорт_ -- для возможности выгрузки существующего Решения из базы данных {dv}. Версия должна быть также доступна на сервере, с которого выгружаются данные.
* _{dv} {sm}. Импорт_ -- для возможности загрузки выгруженного Решения в базу данных {dv}. Версия должна быть также доступна на который загружаются данные.
+
. Срок, в течении которого возможно обновление системы {dv}, указанный в поле лицензии _Возможность обновления до_, не должен быть превышен. Это значит, что на всех серверах {dv}, участвующих в экспорте и импорте Решений, должна сохраняться возможность обновления.

При отсутствии лицензии или истечении срока обновления пользователи не смогут пользоваться функциями экспорта и/или импорта.
