= Функции администратора модуля

[#provide-access]
== Предоставление доступа к модулю

При работе с Менеджером решений выделяется единственная роль -- пользователь. Пользователям предоставляется полный доступ ко всем функциям модуля: настройка подключений, создание и настройка проектов экспорта Решений, экспорт и импорт Решений, и др.

Для предоставления доступа к модулю включите пользователя в локальную группу безопасности *{dv} SolutionManager Administrators* на компьютере с модулем _{sm}_.

[#launch-sm]
== Запуск службы {of-sm}

Запустите службу *{sms-new}*, если она не запущена:

 sudo systemctl restart dvappserver

[#temp-folder-path]
== Настройка пути к временной папке

Администратору необходимо настроить путь к папке, в которую будут сохраняться файлы со списком конфликтов, запрашиваемые пользователем. У <<launch-sm,службы {of-sm}>> должны быть полные права на данную папку.

. Откройте конфигурационный файл модуля:
+
[source,bash,subs=attributes]
----
sudo nano {catalog}/appsettings.json
----
+
. Измените путь к папке в параметре TempFolder:
+
[source]
----
"TempFolder": ".\\Work\\Temp",
----
+
Обратите внимание на использование двойного обратного слеша в пути к папке.
+
. Сохраните изменения.
. Перезапустите службу *{sms-new}*.

[#change-db-connection]
== Изменение подключения к базе данных {of-sm}

После установки {of-sm} подключение к БД с настройками модуля можно изменить в конфигурационном файле:

. Откройте конфигурационный файл модуля в любом текстовом редакторе, например nano:
+
[source,bash,subs=attributes]
----
sudo nano {catalog}/appsettings.json
----
+
. Измените строку подключения к БД в параметре `ConnectionString`, cм. подробнее <<conn-string,ниже>>.
+
// ----
// "StorageSettings": {
//       "ConnectionString": "User ID=postgres;Password=postgres;Host=localhost;Port=5432;Database=SolutionManagerDb",
//       "CommandTimeOut": "300"
//     },
// ----
+
. Сохраните изменения.
. Перезапустите службу {of-sm}.
+
. Измените строку подключения на сервере Службы {ws}, где был установлен компонент "xref:.install-server.adoc#extension[расширение для Службы {ws}]". Подробная инструкция приведена в разделе "xref:dev@workerservice:admin:install.adoc[]"
+
. Перезапустите Службу {ws}.

include::dev@mgmtconsole:admin:install.adoc[tags=string]

[#apply-new-license]
== Применение новой лицензии {dv}

После активации новой лицензии {dv} нужно перезапустить <<launch-sm,службу {of-sm}>>.

[#work-log]
== Журнал работы

.Для анализа работы {of-sm} администратору доступны следующие журналы:
* Журнал работы службы {of-sm} -- хранится в папке `{catalog}/SolutionManager/Logs` на компьютере с модулем _{sm}_.
+
Путь к журналу и уровень протоколирования настраиваются в конфигурационном файле `{catalog}/nlog.config`.
+
* Журнал обработки задач {of-sm} Службой {ws} -- файл `{catalog}/Logs/ГГГ-ММ-ДД_General.log` на компьютере с модулем _Служба {ws}_.
* Журнал со списком загруженных (при импорте Решения) данных -- файл `{catalog}/Logs/ГГГ-ММ-ДД_Import.log` на компьютере с модулем _Служба {ws}_.
+
Пути к журналам и уровни протоколирования настраиваются в конфигурационном файле `{catalog}/nlog.config`.
