= Функции администратора модуля

[#provide-access]
== Предоставление доступа к модулю

При работе с Менеджером решений выделяется единственная роль -- пользователь. Пользователям предоставляется полный доступ ко всем функциям модуля: настройка подключений, создание и настройка проектов экспорта Решений, экспорт и импорт Решений, и др.

Для предоставления доступа к модулю включите пользователя в локальную группу безопасности *{dv} SolutionManager Administrators* на компьютере с модулем _{sm}_.

[#domain]
== Настройка работы в домене

{sm} поддерживает работу в одном или нескольких доменах. Для этого в конфигурационном файле модуля необходимо выполнить настройку доменных каталогов -- параметр `"Catalogs"`:

В конфигурационном файле настройка представлена следующим массивом: `"Catalogs": []`. Настройки вступают в работу, если в массиве присутствует хотя бы одно описание каталога.

[source,json]
----
 "Catalogs": [
  {
   "FullDomainName": "example1.com", <.>
    "NetBiosDomainName": "example1", <.>
    "LdapOptions": { <.>
      "LdapServerAddresses": [ "example1.com" ], <.>
      "AuthType": "Basic", <.>
      "Credential": { <.>
        "UserName": "user@example1.com",
        "Password": "Password"
      }
    }
  }
],
----
<.> `FullDomainName` -- полное имя домена указывается в формате `user@example.com` учётной записи после `@`.
<.> `NetBiosDomainName` -- `NetBios`-имя домена указывается в формате `domain\\user` перед `\\`.
<.> `LdapOptions` -- настройки подключения к LDAP каталогу домена.
<.> `LdapServerAddresses` -- адреса серверов LDAP данного домена. Если адрес соответствует полному имени домену, параметр можно удалить.
<.> `AuthType` -- тип аутентификации в LDAP.
<.> `Credential` -- логин и пароль пользователя для подключения к LDAP-каталогам текущего домена. Пароль для подключения можно зашифровать, см. подробнее в документации по установке системы, раздел "xref:install-linux:ROOT:appendix/account-protection.adoc[]".
// <.> `FullDomainName` -- полное имя домена указывается в формате `user@example.com` учётной записи после `@`.
// <.> `ChallengeTo` -- настройка позволяет переадресовывать запросы от выбранного домена к каталогам указанного домена, см. <<challengeto,далее>>.

.Раздел `Catalogs` может содержать массив настроек вида:
[source,json]
----
 {
    "FullDomainName": "example.com", <.>
    "NetBiosDomainName": "EXAMPLE", <.>
    "LdapOptions": { <.>
      "LdapServerAddresses": [ "example.com" ], <.>
      "AuthType": "Basic", <.>
      "Port": 389, <.>
      "Credential": { <.>
        "UserName": "user@example.com",
        "Password": "Password"
      }
    }
}
----
<.> `FullDomainName` -- полное имя домена указывается в формате `user@example.com` учётной записи после `@`.
<.> `NetBiosDomainName` -- `NetBios`-имя домена указывается в формате `domain\\user` перед `\\`.
<.> `LdapOptions` -- настройки подключения к LDAP каталогу домена.
<.> `LdapServerAddresses` -- адреса серверов LDAP данного домена. Если адрес соответствует полному имени домену, параметр можно удалить.
<.> `AuthType` -- тип аутентификации в LDAP.
<.> `Port` -- порт подключения к LDAP каталогам, перечисленным в `LdapServerAddresses`.
<.> `Credential` -- логин и пароль пользователя для подключения к LDAP-каталогам текущего домена. Пароль для подключения можно зашифровать, см. подробнее в документации по установке системы, раздел "xref:install-linux:ROOT:appendix/account-protection.adoc[]".

[#launch-sm]
== Запуск службы {of-sm}

Запустите службу *{sms-new}*, если она не запущена:

 sudo systemctl start dvsolutionmanager

// [#temp-folder-path]
// == Настройка пути к временной папке
//
// Администратору необходимо настроить путь к папке, в которую будут сохраняться файлы со списком конфликтов, запрашиваемые пользователем. У <<launch-sm,службы {of-sm}>> должны быть полные права на данную папку.
//
// . Откройте конфигурационный файл модуля:
// +
// [source,bash,subs=attributes]
// ----
// sudo nano {catalog}appsettings.json
// ----
// +
// . Измените путь к папке в параметре `"TempFolder"`:
// +
// [source]
// ----
// "TempFolder": ".\\Work\\Temp",
// ----
// +
// Обратите внимание на использование двойного обратного слеша в пути к папке.
// +
// . Сохраните изменения.
// . Перезапустите службу *{sms-new}*.

[#change-db-connection]
== Изменение подключения к базе данных {of-sm}

После установки {of-sm} подключение к БД с настройками модуля можно изменить в конфигурационном файле:

. Откройте конфигурационный файл модуля в любом текстовом редакторе, например nano:
+
[source,bash,subs=attributes]
----
sudo nano {catalog}appsettings.json
----
+
. Измените строку подключения к БД в параметре `ConnectionString`, cм. подробнее в разделе "xref:install.adoc#conn-string[Установка и настройка]" модуля.
+
// ----
// "StorageSettings": {
//       "ConnectionString": "User ID=postgres;Password=postgres;Host=localhost;Port=5432;Database=SolutionManagerDb",
//       "CommandTimeOut": "300"
//     },
// ----
+
. Сохраните изменения.
. Перезапустите службу {of-sm}.
// +
// . Измените строку подключения на сервере Службы {ws}, где был установлен компонент "xref:install.adoc#extension[расширение для Службы {ws}]". Подробная инструкция приведена в разделе "xref:6.1@workerservice:admin:install.adoc[]"
// +
. Перезапустите Службу {ws}.

[#apply-new-license]
== Применение новой лицензии {dv}

После активации новой лицензии {dv} нужно перезапустить <<launch-sm,службу {of-sm}>>.

[#work-log]
== Журнал работы

.Для анализа работы {of-sm} администратору доступны следующие журналы:
* Журнал работы службы {of-sm} -- хранится в папке `{log}` на компьютере с модулем _{sm}_.
+
Путь к журналу и уровень протоколирования настраиваются в конфигурационном файле модуля `{catalog}appsettings.json`.
+
* Общий журнал работы {of-sm} -- файл `{log}/ГГГГ-ММ-ДД_SolutionManager.log` на компьютере с модулем _Служба {ws}_.
// * Журнал обработки задач {of-sm} Службой {ws} -- файл `{log}/ГГГГ-ММ-ДД_General.log` на компьютере с модулем _Служба {ws}_.
// * Журнал со списком загруженных (при импорте Решения) данных -- файл `{log}/ГГГГ-ММ-ДД_Import.log` на компьютере с модулем _Служба {ws}_.
+
Пути к журналам и уровни протоколирования настраиваются в конфигурационном файле `{catalog}appsettings.json`.
