= Установка и настройка

== Состав установочного комплекта

. Пакет установки {of-sm}: `{dv} SolutionManager.msi`.
. Пакет установки расширения Службы {ws} для {of-sm}: `{dv} Solution manager extension for Worker service.msi`.
. `{dv} Solution manager.exe` -- пакетный установщик модулей _{sm}_, _Служба {ws}_ и _Расширение Службы {ws} для {of-sm}_.

[#options]
== Варианты установки {of-sm}

.{sm} может быть установлен двумя способами:
* Обычная установка.
+
Администратору нужно последовательно установить модули _{sm}_ и _Расширение Службы {ws} для {of-sm}_ из отдельных пакетов установки. Модуль "Служба {ws}" должен быть установлен заранее.
+
Данный вариант установки подходит для совместной и раздельной установки _{of-sm}_ и _Службы {ws}_.
+
* Установка с помощью пакетного установщика.
+
Пакетный установщик включает в себя установщики трех модулей: _{sm}_, _Служба {ws}_ и _Расширение Службы {ws} для {of-sm}_. Администратор может использовать пакетный установщик для установки всех компонентов, необходимых для работы {of-sm}.
+
Данный вариант установки подходит для совместной установки _{of-sm}_ и _Службы {ws}_.

