:of: {of-sm}
:wt: solutionmanager

= Установка и настройка

// == Состав установочного комплекта

// . Пакет установки {of-sm}: `{dv} SolutionManager.msi`.
// . Пакет установки расширения Службы {ws} для {of-sm}: `{dv} Solution manager extension for Worker service.msi`.
// . `{dv} Solution manager.exe` -- пакетный установщик модулей _{sm}_, _Служба {ws}_ и _Расширение Службы {ws} для {of-sm}_.

// [#options]
// == Варианты установки {of-sm}
//
// .{sm} может быть установлен двумя способами:
// * Обычная установка.
// +
// Администратору нужно последовательно установить модули _{sm}_ и _Расширение Службы {ws} для {of-sm}_ из отдельных пакетов установки. Модуль "Служба {ws}" должен быть установлен заранее.
// +
// Данный вариант установки подходит для совместной и раздельной установки _{of-sm}_ и _Службы {ws}_.
// +
// * Установка с помощью пакетного установщика.
// +
// Пакетный установщик включает в себя установщики трех модулей: _{sm}_, _Служба {ws}_ и _Расширение Службы {ws} для {of-sm}_. Администратор может использовать пакетный установщик для установки всех компонентов, необходимых для работы {of-sm}.
// +
// Данный вариант установки подходит для совместной установки _{of-sm}_ и _Службы {ws}_.

Пользователь, выполняющий настройку {dv}, должен являться локальным администратором (быть указанным в файле sudoers).

[#linux]
== Установка на Linux

include::dev@platform:admin:partial$install.adoc[]
+
Основные настройки, которые нужно сделать:
+
[source,json]
----
{
  "Docsvision": {
    "WebClient": {
      "Authentication": {
        "DefaultDomain": "DOMAIN.COM" <.>
      },
      "Server": {
        "SessionManagerConnection": {
          "ConnectionAddress": "http://dvserver.domain.com:5000"  <.>
        }
      }
    }
  },
  "Ldap": { <.>
    "AuthType": "Basic", <.>
    "Credential": {
      "UserName": "account@domain.com", <.>
      "Password": "password" <.>
    }
  },
  "DataProtectCertificateThumbprint": "thumbprint", <.>
  "SystemUserAccount": "account@domain.com", <.>
  "SystemUserPassword": "password", <.>
}
----
<.> `DefaultDomain` -- домен по умолчанию в формате FQDN.
<.> `ConnectionAddress` -- адрес сервера {dv}.
<.> `Ldap` -- имя и пароль учётной записи, под которой процесс обращается к ActiveDirectory. +
Пароль можно указывать в открытом или в зашифрованном виде, см. подробнее о шифровании в документации по установке системы, раздел "xref:dev@install-linux::account-protection.adoc[]"
+
<.> `AuthType` -- тип аутентификации: `Basic` -- аутентификация через LDAP, `Oauth` -- аутентификация через ЕСИА или Azure.
<.> `UserName` -- логин пользователя модуля для аутентификации LDAP.
<.> `Password` -- пароль учётной записи пользователя для аутентификации LDAP.
<.> `DataProtectCertificateThumbprint` -- отпечаток закрытого ключа шифрования SHA1. +
Указывается без двоеточия, например, `D8602179888DC8402B393F11DCA16A3376DDF879`, см. подробнее в документации по установке системы, раздел "xref:dev@install-linux::account-protection.adoc[]". +
Если шифровать пароль системной учётной записи не планируется, параметр можно удалить.
<.> `SystemUserAccount` -- имя системной учётной записи {dv} в формате UPN.
<.> `SystemUserPassword` -- пароль системной учётной записи рекомендуется хранить в зашифрованном виде. Подробнее про шифрование см. в документации по установке системы, раздел "xref:install-linux::account-protection.adoc[]".
// end::linux[]
+
. Запустите службу модуля:
+
[source,bash]
----
sudo systemctl start dvwebclient
----

[#uninstall]
== Удаление модуля и расширения для Службы {ws}

_{sm}_ и _Расширение для Службы {ws}_ удаляются стандартным образом средствами ОС:

[source,bash,subs=attributes]
----
sudo apt-get purge docsvision-{wt}
----

// [WARNING]
// ====
// _Расширение для Службы {ws}_ может быть удалено только при установленном модуле _{dv} Служба {ws}_. Если удаляются оба модуля, расширение следует удалять перед удалением "Службы {ws}".
// ====

