= Установка и настройка

== Состав установочного комплекта

. Пакет установки {of-sm}: `{dv} 5 SolutionManager.msi`.
. Пакет установки расширения Службы {ws} для {of-sm}: `{dv} 5 Solution manager extension for Worker service.msi`.
. `{dv} 5 Solution manager.exe` -- пакетный установщик модулей "{sm}", "Служба {ws}" и "Расширение Службы {ws} для {of-sm}".

[#options]
== Варианты установки {of-sm}

.{sm} может быть установлен двумя способами:
* Классическая установка.
+
Администратору нужно последовательно установить модули "{sm}" и "Расширение Службы {ws} для {of-sm}" из отдельных пакетов установки. Модуль "Служба {ws}" должен быть установлен заранее.
+
Данный вариант установки подходит для совместной и раздельной установки "{of-sm}" и "Службы {ws}".
+
* Установка с помощью пакетного установщика.
+
Пакетный установщик включает в себя установщики трех модулей: "{sm}", "Служба {ws}" и "Расширение Службы {ws} для {of-sm}". Администратор может использовать пакетный установщик для установки всех компонентов, необходимых для работы {of-sm}.
+
Данный вариант установки подходит для совместной установки "{of-sm}" и "Службы {ws}".

