= Типы конфликтов импорта

Следующие конфликты могут быть обнаружены при проверке загружаемых данных перед импортом Решения.

* *КОНФЛИКТЫ ДАННЫХ*.
** *InvalidCardTypeId*. Возникает, если тип импортируемой карточки не зарегистрирован в целевой БД.
** *GlobalUniqueViolated*. Возникает, если импортируемая карточка нарушает требование уникальности значения поля, установленное на уровне БД. Данный конфликт связан с тем, что значение поля с признаком "Unique globally" в импортируемой карточке совпадает со значением данного поля в существующей карточке.
** *CardUniqueViolated*. Возникает, если импортируемая карточка нарушает требование уникальности значения поля, установленное на уровне экземпляра карточки. В схеме карточки для поля установлен признак уникальности "Unique within card".
** *SectionUniqueViolated*. Возникает, если импортируемая карточка нарушает требование уникальности значения поля, установленное на уровне секции экземпляра карточки. В схеме карточки для поля установлен признак уникальности "Unique within section".
** *TreeUniqueViolated*. Возникает, если импортируемая карточка нарушает требование уникальности значения поля, установленное на уровне всего дерева иерархической секции. В схеме карточки для поля установлен признак уникальности "Unique within tree".
** *SecondRowInStructSection*. Возникает, если импортируемые данные добавляют новую строку в "плоскую" секцию. Данный конфликт связан с тем, что из-за различий идентификаторов строк одной "плоской" секции в импортируемых и существующих данных, при импорте в секцию будет добавлена вторая строка, что запрещено для данного типа секций.
** *TreeCycleDetected*. Возникает, если в импортируемых данных строка A является родительской для строки Б, а в целевой БД -- строка Б является родительской для А, из-за чего при импорте будет произведена попытка перемещения родительской строки в дочернюю.
** *InvalidEnumValue*. Возникает, если значение поля типа ENUM в импортируемых данных, отсутствует в списке возможных значений данного поля в целевой БД.
** *InvalidRowReference*. Возникает, если значение поля с типом REFID в импортируемых данных ссылается на строку, которой нет в целевой БД и нет в импортируемых данных.
** *InvalidCardReference*. Возникает, если значение поля с типом REFCARDID в импортируемых данных ссылается на карточку, которой нет в целевой БД и нет в импортируемых данных.
** *Custom*. Логика проверки данного конфликта реализована в расширении {of-sm}.
* *КОНФЛИКТЫ МЕТАДАННЫХ*.
** *DuplicatedFieldName*. Возникает, если поля с аналогичными названиями в импортируемых данных и в целевой БД имеют разные идентификаторы.
** *DuplicatedFieldId*. Возникает, если поля с аналогичными идентификаторами в импортируемых данных и в целевой БД имеют разные имена.
** *DuplicatedSectionAlias*. Возникает, если секции с аналогичными названиями в импортируемых данных и в целевой БД имеют разные идентификаторы.
** *DuplicatedSectionId*. Возникает, если секции с аналогичными идентификаторами в импортируемых данных и в целевой БД имеют разные имена.
** *InvalidReferencedCardTypeId*. Возникает, если поле с типом REFID или REFCARDID в импортируемых данных ссылается на тип карточек, которого нет в целевой БД.
** *InvalidReferencedSectionTypeId*. Возникает, если поле с типом REFID или REFCARDID в импортируемых данных ссылается на тип секции, которой нет в целевой БД и в импортируемых данных.
** *InvalidReferencedField*. Возникает, если поле с типом REFID или REFCARDID в импортируемых данных и поле в целевой БД ссылаются на разные типы карточек или типы секций.
** *IncompatibleFieldTypeChange*. Возникает, если тип поля в импортируемых данных несовместим с типом данного поля в целевой БД, или различается список возможных значений поля с типом ENUM.
** *InvalidCardTypeId*. Возникает, если расширенная секции в импортируемых данных расширяет тип карточек, отсутствующий в целевой БД.
** *InvalidParentSectionId*. Возникает, если родительская секция импортируемой дочерней секции отсутствует в целевой БД и в импортируемых данных.
** *Custom*. Логика проверки данного конфликта реализована в расширении {of-sm}.
