= Варианты решения конфликтов импорта

Следующие варианты решения конфликтов могут быть применены к данным перед импортом Решения.

* *Отредактировать объект вручную в базе-приемнике*. Данный вариант предполагает, что пользователь самостоятельно исправит в целевой БД конфликтующие данные.
* *Заменить старый объект новым*. Заменяет значение ROWID в импортируемых данных на значение из целевой БД. Данное решение предлагается для конфликтов: TreeUniqueViolated, SectionUniqueViolated.
* *Поменять поле импортируемого объекта*. Заменяет идентификатор поля в импортируемых данных на новый. Данное решение предлагается для конфликтов: TreeUniqueViolated, SectionUniqueViolated.
* *Заменить ID на Guid.Empty*. Изменяет идентификатор ссылки на "00000000-0000-0000-0000-000000000000". Данное решение предлагается для конфликта: InvalidRowReference.
* *Не импортировать секцию метаданных*. Удаляет из импортируемых данных вызывавшую конфликт секцию. Данное решение предлагается для конфликта: DuplicatedSectionAlias.
* *Не импортировать поле метаданных*. Удаляет из импортируемых данных вызывавшее конфликт поле. Данное решение предлагается для конфликта: DuplicatedFieldName.
* *Заменить старую роль новой*. Заменяет идентификатор роли в импортируемых данных на значение из целевой БД. Данное решение предлагается для конфликта: Custom при нарушении уникальности имени для роли.
* *Поменять имя импортируемой роли*. Заменяет идентификатор роли в импортируемых данных на новый. Данное решение предлагается для конфликта: Custom при нарушении уникальности имени для роли.
* *Заменить старую разметку новой*. Заменяет идентификатор разметки в импортируемых данных на значение из целевой БД. Данное решение предлагается для конфликт: Custom при нарушении уникальности имени для разметки.
* *Поменять имя импортируемой разметки*. Заменяет идентификатор разметки в импортируемых данных на новый. Данное решение предлагается для конфликта: Custom при нарушении уникальности имени для разметки.
