= Сообщения об ошибках

* *"Доступ запрещён"*
+
Возникает при запуске {of-sm}, если у пользователя отсутствуют права на работу с программой.
+
_Обратитесь к администратору._
* *"Нельзя удалить соединение - есть зависимые проекты"*
+
Возникает при попытке удаления соединения, которое используется в настройках проектов экспорта.
+
_Удалите зависимые проекты._
* *"БД подключения использует динамические метаданные. Рекомендуем изменить режим использования метаданных на расширенные"*
+
Возникает при настройке экспорта расширенных метаданных, если БД {dv} работает в режиме с динамическими метаданными.
+
_Обратитесь к администратору._
* *"Выполнение операций невозможно. Восстановите работу службы процессов"*
+
Возникает, если остановлен/недоступен "Сервис {ws}", обрабатывающий задания {of-sm}.
+
_Обратитесь к администратору._
* *"Для вкладки заданы некорректные настройки: "*
+
Может возникать при открытии окна настроек проекта экспорта, если в настройках выбраны данные Решения, которые были удалены из {dv}. Также может возникать при смене БД {dv} в настройках подключения к системе {dv}, если в БД отсутствуют данные, выбранные в настройках проекта решения.
+
_В настройках проекта Решения снимите выбор с данных, которые не существуют в системе {dv}, или создайте проект заново._
* *"При экспорте проекта произошла ошибка: Соединение уже используется. Выполняется операция экспорта"*
+
Может возникать при запуске экспорта Решения, если соединение с сервером {dv}, указанное в проекте Решения, используется в другом Решении, экспорт которого уже выполняется.
+
_Дождитесь завершения экспорта Решения, в котором используется соединение с сервером {dv} выгружаемого Решения._
* *"Обнаружены конфликты, необходимо определить способы разрешения"*
+
Может возникнуть при загрузке данных в целевую БД, если при проверке данных обнаружены конфликты.
+
_Выберите способы решения конфликтов или установите флаг "Не проверять конфликты перед импортом" на странице "Импорт обновления"._
* "Некорректная лицензия. Для указанного подключения в лицензии отсутствует разрешение для использования Экспорта"
+
Может возникать при сохранении проекта экспорта Решения и выполнении экспорта, если лицензия {dv} не содержит опции, разрешающей экспорт Решений.
+
_Обратитесь к администратору._
* *"Некорректная лицензия. Для указанного подключения в лицензии отсутствует разрешение для использования Импорта"*
+
Может возникать при выборе подключения при выполнении импорта Решения и при запуске импорта Решения, если лицензия {dv} не содержит опции, разрешающей импорт Решений.
+
_Обратитесь к администратору._
* *"Некорректная лицензия"*
+
Может возникать при создании и редактировании подключения к серверу {dv}, если лицензия {dv} не содержит опций, разрешающих импорт или экспорт Решений. Также может возникать, если срок обновления {dv} истёк.
+
_Обратитесь к администратору._
