= Выполняемые функции и задачи

.Перенос Решения между серверами и/или базами данных {dv} включает несколько этапов:
. Предварительная настройка.
+
На данном этапе пользователь должен настроить подключение, как минимум, к двум серверам или БД {dv}:
+
* К серверу, на котором настроено выгружаемое Решение.
* К серверу, в БД которого Решение будет загружаться.
+
Пользователь может настроить сразу несколько подключений, как к серверам с настроенными Решениями, так и к серверам, на которые импортируются Решения.
+
. Настройка проекта экспорта Решения.
+
Пользователь должен создать _проект экспорта_ и выбрать настройки Решения, которые нужно выгружать. В проекте экспорта также выбирается подключение к серверу {dv}, данные которого экспортируются.
+
Пользователь может создать несколько _проектов экспорта_ для выгрузки разных данных Решения с одного сервера {dv}.
+
. Экспорт Решения.
+
На данном этапе пользователь должен выполнить экспорт Решения для выбранного проекта экспорта. По одному _проекту экспорта_ данные Решения могут выгружаться многократно с указанием версии выгрузки -- версия Решения.
+
Версия Решения сохраняется в БД {of-sm} и, если требуется, может быть загружена на компьютер пользователя (например, для передачи заказчику).
+
. Импорт Решения.
+
.На данном этапе пользователю нужно выполнить несколько действий:
.. Выбрать импортируемую версию Решения. Версия выбирается из ранее экспортированных версий или из файла.
.. Выполнить проверку на наличие конфликтов между загружаемой версией Решения и данными, которые уже имеются (или, наоборот, отсутствуют) в БД. После завершения проверки пользователь может выбрать способы исправления обнаруженных конфликтов.
.. Выполнить импорт Решения.
.. Если импорт завершился с ошибкой, пользователь должен решить обнаруженные конфликты и повторить импорт.
